#! /usr/bin/env python3.7
"""
=========================================================
LordCommander
=========================================================
LordCommander is a python program to run a shell command 
recursively through predefined directories.

Version: 2.0
Author: Sowren Sen
Email: sowrensen@gmail.com
"""


import shelve
import os
import sys
from controllers import Controller


class LordCommander:
    """Event horizon of the program."""
    # The shelve file for storing directories
    dirs = None
    # The shelve file for storing credentials
    creds = None

    def read_files(self):
        """Read files or create them if doesn't exist."""
        if not os.path.exists('.files'):
            os.mkdir('.files')
        self.dirs = shelve.open('./.files/dirs')
        self.creds = shelve.open('./.files/creds')

    def main(self):
        """Initiate and run main controller."""
        self.read_files()
        # Initiate and call main controller
        call = Controller(self.dirs, self.creds, sys.argv[2])
        call.pilot()


lc = LordCommander()
lc.main()
